version: "3.9"

services:
  api-gateway:
    build: ./api-gateway
    container_name: kg_api_gateway
    networks:
      - proxy-network
      - backend-network
    ports:
      - "5000:5000"

  auth-service:
    build: ./auth-service
    container_name: kg_auth_service
    networks:
      - backend-network
    volumes:
      - ./data:/app/data

  destination-service:
    build: ./destination-service
    container_name: kg_destination_service
    networks:
      - backend-network
    volumes:
      - ./data:/app/data

  itinerary-service:
    build: ./itinerary-service
    container_name: kg_itinerary_service
    networks:
      - backend-network
    volumes:
      - ./data:/app/data

  recommendation-service:
    build: ./recommendation-service
    container_name: kg_recommendation_service
    networks:
      - backend-network
    volumes:
      - ./data:/app/data

  frontend:
    build: ./frontend
    container_name: kg_frontend
    networks:
      - proxy-network
    ports:
      - "18082:80"

networks:
  proxy-network:
    external: true
  backend-network:
    driver: bridge
